linters:
  rubocop:
    fixer: true
  csslint: {  }
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
     - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
fixers:
  enable: true

