linters:
  rubocop:
    display_cop_names: true
    # indicate where is the config file for stylelint
    config: './rubocop.yml'
    csslint: {  }
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"


